---
- name: nginx setup
  hosts: server
  become: yes
  become_method: sudo
  tasks:
    - name: Enable to install NGINX.
      shell: "amazon-linux-extras enable nginx1"
    - name: nginx install
      yum:
        name: nginx
        state: latest
